### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/PoliNetworkBot#14]
https://github.com/PoliNetworkOrg/PoliNetworkBot/actions/runs/6051405724

**Comment by Eliaxie** [comment]
fix problems introduced in https://github.com/PoliNetworkOrg/PoliNetworkBot/pull/13, revert the directory structure with the library inside the project, the test projects have apparently disappeard, the dockerfiles have been deleted @OneEyeDoll @angeousta

**Comment by angeousta** [comment]
in teoria fixata quindi chiudo, se ritenete vada riaperta, riaprite pure
