### ISSUE TITLE
Codecov checks fail

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/PoliNetworkBot#21]
![immagine](https://github.com/PoliNetworkOrg/PoliNetworkBot/assets/132761637/4f6a2d3f-f885-434a-ac59-5a73837fa3cc)

**Comment by Eliaxie** [comment]
As intended, test the code more.
If it's not possible, you can safely ignore it

**Comment by angeousta** [comment]
Non dovrebbe segnarlo come skipped e non come failed?
