### ISSUE TITLE
Actions/Builds broken

### ISSUE THREAD

**Issue by angeousta** [PoliNetworkOrg/PoliNetworkBot#3]

**Comment by Eliaxie** [comment]
https://github.com/PoliNetworkOrg/PoliNetworkBot/pull/12
ci should be ok, cd we will see when we merge

**Comment by Eliaxie** [comment]
https://github.com/PoliNetworkOrg/PoliNetworkBot/commit/72256c30863321dd24d4dd66f5b5b3f034d68a76
